(function () {
  const params = new URLSearchParams(location.search);
  const statuses = ["saved", "running", "applied", "failed"];
  const labels = { saved: "Saved", running: "In progress", applied: "Applied", failed: "Failed" };
  const frame = document.getElementById("gqo-live-frame");
  const overlay = document.getElementById("gqo-live-overlay");
  const key = `gqo-live:${location.pathname}:${params.get("actual") || ""}`;
  const state = { targetId: "", mode: params.get("mode") === "comment" ? "comment" : "edit", filter: "all", collapsed: false, items: load(), targets: [] };

  function byId(id) { return document.getElementById(id); }
  function actualUrl() { try { const url = new URL(params.get("actual") || ""); return ["http:", "https:"].includes(url.protocol) ? url.href : ""; } catch { return ""; } }
  function proxyUrl() { return "/__gqo/actual/"; }
  function page() { try { return new URL(actualUrl()).pathname.split("/").pop() || "actual"; } catch { return "actual"; } }
  function status(value) { if (["running", "applied", "failed"].includes(value)) return value; return "saved"; }
  function normalize(items) { return Array.isArray(items) ? items.map((item) => ({ ...item, status: status(item.status) })) : []; }
  function load() { try { return normalize(JSON.parse(localStorage.getItem(key) || "[]")); } catch { return []; } }
  function writeStorage() { try { localStorage.setItem(key, JSON.stringify(state.items)); } catch {} }
  function doc() { try { return frame.contentDocument; } catch { return null; } }
  function win() { try { return frame.contentWindow; } catch { return null; } }
  function visible(element) { const rect = element.getBoundingClientRect(); const style = win().getComputedStyle(element); return rect.width > 0 && rect.height > 0 && rect.bottom >= 0 && rect.right >= 0 && rect.top <= win().innerHeight && rect.left <= win().innerWidth && style.visibility !== "hidden" && style.display !== "none"; }
  function scopeFor(id) { if (id === "global") return "global"; return doc()?.querySelector(`[data-gqo-id="${CSS.escape(id)}"]`)?.getAttribute("data-gqo-scope") || "element"; }
  function discoverTargets() {
    const root = doc();
    if (!root) return [{ id: "global", label: "Global", scope: "global", editable: "", text: "", bounds: null }];
    const targets = [...root.querySelectorAll("[data-gqo-id]")].filter(visible).map((element) => {
      const rect = element.getBoundingClientRect();
      const id = element.getAttribute("data-gqo-id") || "";
      return { id, label: id, scope: element.getAttribute("data-gqo-scope") || "element", editable: element.getAttribute("data-gqo-editable") || "", text: (element.textContent || "").trim().replace(/\s+/g, " ").slice(0, 160), bounds: { x: Math.round(rect.x), y: Math.round(rect.y), width: Math.round(rect.width), height: Math.round(rect.height) } };
    }).filter((target) => target.id);
    return [{ id: "global", label: "Global", scope: "global", editable: "", text: "", bounds: frame.getBoundingClientRect() }].concat(targets);
  }
  function changeRequests() { return state.items.filter((item) => item.type === "change-request"); }
  function requestFrom(item) { return { id: item.id.replace(/^comment-/, "change-"), sourceCommentId: item.id, targetId: item.targetId, page: item.page, scope: item.scope || scopeFor(item.targetId), requestedChange: item.comment, rationale: "Captured from live visual review edit request.", acceptanceSignal: "Updated UI matches the requested live review change.", priority: item.severity, status: status(item.status), createdAt: item.createdAt, createdBy: "visual-review", savedAt: item.savedAt, savedBy: "visual-review", checks: { workStart: { targetConfirmed: true, requestActionable: true, scopeConfirmed: true, acceptanceSignalDefined: true, dependenciesRecorded: false }, completion: { artifactUpdated: false, acceptanceSignalObserved: false, documentsAligned: false, openQuestionsPreserved: true, changedArtifactsRecorded: false } } }; }
  function markdown() { return ["# Visual Review Comments", ""].concat(state.items.flatMap((item) => [`## ${item.targetId}`, "", `- Type: ${item.type}`, `- Severity: ${item.severity}`, `- Scope: ${item.scope || scopeFor(item.targetId)}`, `- Status: ${item.status}`, `- Mode: ${item.mode}`, `- Page: ${item.page}`, `- Created: ${item.createdAt}`, "", "```", item.comment.replaceAll("`", "\\`"), "```", ""])).join("\n"); }
  function syncPayload() { return { schema: "gqo.visual-review-state.v1", source: page(), actual: actualUrl(), savedAt: new Date().toISOString(), targets: state.targets, comments: state.items, changeRequests: { schema: "gqo.change-requests.v1", source: page(), actual: actualUrl(), exportedAt: new Date().toISOString(), requests: changeRequests().map(requestFrom) }, markdown: markdown() }; }
  function sync() { writeStorage(); fetch("/__gqo/save", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(syncPayload()) }).catch(() => {}); }
  function refresh() { fetch(`/__gqo/state?t=${Date.now()}`, { cache: "no-store" }).then((r) => r.ok ? r.json() : {}).then((payload) => { if (Array.isArray(payload.comments)) state.items = normalize(payload.comments); render(); }).catch(render); }
  function badge(value) { const span = document.createElement("span"); span.className = `gqo-status gqo-status-${status(value)}`; span.textContent = labels[status(value)]; return span; }
  function updateTargets() { state.targets = discoverTargets(); const select = byId("gqo-target"); select.textContent = ""; for (const target of state.targets) select.append(new Option(target.label, target.id)); drawOverlay(); }
  function drawOverlay() { overlay.textContent = ""; const frameRect = frame.getBoundingClientRect(); for (const target of state.targets.filter((target) => target.id !== "global" && target.bounds)) { const box = document.createElement("button"); box.className = "gqo-live-target"; box.type = "button"; box.style.left = `${frameRect.left + target.bounds.x}px`; box.style.top = `${frameRect.top + target.bounds.y}px`; box.style.width = `${target.bounds.width}px`; box.style.height = `${target.bounds.height}px`; box.title = target.id; box.addEventListener("click", () => openPanel(target.id)); overlay.append(box); } }
  function createShell() {
    const toolbar = document.createElement("div"); toolbar.className = "gqo-toolbar";
    toolbar.innerHTML = `<div class="gqo-toolbar-title"><strong>GIQO Live Review</strong><a href="${actualUrl()}" target="_blank" rel="noreferrer">Actual screen</a><span id="gqo-sync">Auto-save ready</span></div><div class="gqo-toolbar-controls"><label>Mode <select id="gqo-mode"><option value="comment">Comment</option><option value="edit">Edit request</option></select></label><label>Status <select id="gqo-filter"><option value="all">All</option></select></label><label>Target <select id="gqo-target"></select></label><button id="gqo-refresh" type="button">Refresh</button><button id="gqo-toggle" type="button" aria-expanded="true">Hide feedback</button><button id="gqo-clear" type="button">Clear</button></div>`;
    document.body.prepend(toolbar); for (const value of statuses) byId("gqo-filter").append(new Option(labels[value], value));
    const panel = document.createElement("aside"); panel.className = "gqo-panel"; panel.hidden = true; panel.innerHTML = `<strong id="gqo-panel-title">GIQO edit request</strong><p id="gqo-target-label"></p><label>Severity<select id="gqo-severity"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label>Comment<textarea id="gqo-comment" placeholder="Write feedback or requested edit"></textarea></label><div class="gqo-panel-actions"><button id="gqo-cancel" type="button">Cancel</button><button id="gqo-save" type="button">Save</button></div>`; document.body.append(panel);
    const list = document.createElement("aside"); list.className = "gqo-comment-list"; list.innerHTML = `<div class="gqo-comment-list-header"><strong>Saved feedback</strong><button id="gqo-list-toggle" type="button" aria-expanded="true">Minimize</button></div><div id="gqo-comments"></div>`; document.body.append(list);
    return panel;
  }
  function openPanel(id) { state.targetId = id; byId("gqo-target").value = id; byId("gqo-panel-title").textContent = state.mode === "edit" ? "GIQO edit request" : "GIQO comment"; byId("gqo-target-label").textContent = id === "global" ? "Global project feedback" : id; byId("gqo-comment").value = ""; document.querySelector(".gqo-panel").hidden = false; byId("gqo-comment").focus(); }
  function savePanel() { const comment = byId("gqo-comment").value.trim(); if (!state.targetId || !comment) return; state.items.push({ id: `comment-${Date.now()}`, targetId: state.targetId, page: page(), mode: state.mode, scope: scopeFor(state.targetId), type: state.mode === "edit" ? "change-request" : "question", severity: byId("gqo-severity").value, comment, createdAt: new Date().toISOString(), savedAt: new Date().toISOString(), status: "saved" }); document.querySelector(".gqo-panel").hidden = true; sync(); render(); }
  function renderList() { const box = byId("gqo-comments"); box.textContent = ""; const items = state.filter === "all" ? state.items : state.items.filter((item) => item.status === state.filter); if (!items.length) { const empty = document.createElement("p"); empty.className = "gqo-empty"; empty.textContent = state.filter === "all" ? "No saved comments or edit requests." : "No saved feedback matches this status."; box.append(empty); } for (const item of items) { const card = document.createElement("article"); card.className = "gqo-list-item"; const title = document.createElement("b"); title.textContent = `${item.targetId} · ${item.type}`; const body = document.createElement("p"); body.textContent = item.comment; card.append(title, body, badge(item.status)); box.append(card); } }
  function render() { renderList(); document.body.dataset.gqoFeedbackCollapsed = state.collapsed ? "true" : "false"; }
  function setCollapsed(value) { state.collapsed = value; byId("gqo-toggle").textContent = value ? "Show feedback" : "Hide feedback"; byId("gqo-list-toggle").textContent = value ? "Show" : "Minimize"; render(); }
  function wire(panel) { byId("gqo-mode").value = state.mode; byId("gqo-mode").addEventListener("change", (event) => { state.mode = event.target.value; }); byId("gqo-filter").addEventListener("change", (event) => { state.filter = event.target.value; renderList(); }); byId("gqo-target").addEventListener("change", (event) => openPanel(event.target.value)); byId("gqo-refresh").addEventListener("click", () => { updateTargets(); refresh(); }); byId("gqo-toggle").addEventListener("click", () => setCollapsed(!state.collapsed)); byId("gqo-list-toggle").addEventListener("click", () => setCollapsed(!state.collapsed)); byId("gqo-cancel").addEventListener("click", () => { panel.hidden = true; }); byId("gqo-save").addEventListener("click", savePanel); byId("gqo-clear").addEventListener("click", () => { state.items = []; sync(); render(); }); addEventListener("resize", drawOverlay); frame.addEventListener("load", () => { updateTargets(); sync(); try { doc().addEventListener("click", (event) => { const target = event.target.closest?.("[data-gqo-id]"); if (target) { event.preventDefault(); event.stopPropagation(); openPanel(target.getAttribute("data-gqo-id")); } }, true); } catch {} }); }
  function init() { if (!actualUrl()) { document.body.textContent = "Missing --actual URL."; return; } const panel = createShell(); frame.src = proxyUrl(); wire(panel); refresh(); render(); }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init); else init();
})();
